/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_game_free(a: number): void;
export function game_new(): number;
export function game_event_handler(a: number, b: number, c: number): void;
export function game_touch_event_handler(a: number, b: number, c: number): void;
export function game_update(a: number, b: number): number;
export function game_is_game_over(a: number): number;
export function game_get_score(a: number): number;
export function game_get_width(a: number): number;
export function game_get_height(a: number): number;
export function game_get_seconds(a: number): number;
export function game_get_offset_height(a: number): number;
export function game_get_level(a: number): number;
export function game_get_rows_completed(a: number): number;
export function game_get_hold_piece(a: number): number;
export function game_get_queued_pieces(a: number): number;
export function game_get_cells(a: number): number;
export function game_get_pieces(a: number): number;
export function game_get_piece_bounding_box(a: number): number;
export function game_get_piece_type(a: number): number;
export function game_get_piece_position(a: number): number;
export function game_get_shadow_piece_position(a: number): number;
export function __wbg_point_free(a: number): void;
export function __wbg_get_point_x(a: number): number;
export function __wbg_set_point_x(a: number, b: number): void;
export function __wbg_get_point_y(a: number): number;
export function __wbg_set_point_y(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
